<?xml version="1.0"?>
<module name="$ModuleName$">
    <file name="Module" type="template" />
    <file name="autoload_classmap" type="source" />
    
    <directory name="config">
        <file name="module.config" type="template" />
    </directory>
    <directory name="src">
        <directory name="$ModuleName$">
            <directory name="Controller" />
            <directory name="Form" />
            <directory name="Model" />
        </directory>
    </directory>
    <directory name="view">
        <directory name="$ModuleNameLower$">
            <directory name="$ModuleNameLower$" />
        </directory>
    </directory>
</module>