/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package co.ke.nerdonia.ndzf2modules;

import java.awt.TextField;
import javax.swing.JPanel;

public final class ZF2ModuleCreatorVisualPanel1 extends JPanel {

    /**
     * Creates new form ZF2ModuleCreatorVisualPanel1
     */
    public ZF2ModuleCreatorVisualPanel1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "Module Name";
    }
    
    public String getModuleName(){
        return TextFieldModuleName.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TextFieldModuleName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setName(org.openide.util.NbBundle.getMessage(ZF2ModuleCreatorVisualPanel1.class, "ZF2ModuleCreatorVisualPanel1.name")); // NOI18N

        TextFieldModuleName.setText(org.openide.util.NbBundle.getMessage(ZF2ModuleCreatorVisualPanel1.class, "ZF2ModuleCreatorVisualPanel1.TextFieldModuleName.text")); // NOI18N
        TextFieldModuleName.setName("TextFieldModuleName"); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(ZF2ModuleCreatorVisualPanel1.class, "ZF2ModuleCreatorVisualPanel1.jLabel1.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(TextFieldModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(118, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TextFieldModuleName;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
